apiVersion: extensions/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: codesuite-demo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: codesuite-demo
spec:
  type: LoadBalancer
  selector:
    app: hello-world
  ports:
  - name: hello-port
    port: 80
    targetPort: 80
    protocol: TCP
